# Generated by Django 2.0.7 on 2018-07-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genlookuplistview',
            name='id',
            field=models.FloatField(primary_key=True, serialize=False),
        ),
    ]
