# Generated by Django 2.0.5 on 2018-07-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genlookuplistview',
            name='id',
        ),
        migrations.AddField(
            model_name='genlookuplistview',
            name='db',
            field=models.BigIntegerField(blank=True, null=True, primary_key=True, serialize=False),
        ),
    ]
