# Generated by Django 2.0.5 on 2018-07-25 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20180725_1533'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='genlookuplistview',
            table='GEN_LOOKUP_LIST_VIEW',
        ),
    ]
