# Generated by Django 2.0.5 on 2018-07-26 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20180725_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genlookuplistview',
            options={'managed': False},
        ),
    ]
